networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "3300:3300"
    networks:
      - backend
    environment:
      POSTGRES_DB: "kilocal_api"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql