# Production Docker Compose
networks:
    apiserver:
        driver: bridge
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: ghcr.io/ansengarvin/backend:latest
        container_name: backend
        user: "node"
        working_dir: /app
        expose:
            - "8000"
        ports:
            - 8000:8000
        networks:
            - apiserver
        command: "npm start"
volumes:
    node_modules:
