services:
    frontend:
        environment:
            - NODE_ENV=development
    backend:
        environment:
            - NODE_ENV=development
            - FIREBASE_AUTH_EMULATOR_HOST=host.docker.internal:9099
