# docker compose for local testing
networks:
  apiserver:
    driver: bridge
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    networks:
      - apiserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/ansengarvin/test-backend:latest
    container_name: backend
    user: "node"
    working_dir: /home/node/app
    expose:
      - "8000"
    ports:
      - 8000:8000
    networks:
      - apiserver
    volumes:
      - ./backend:/home/node/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS="./keys/service.json"
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    command: "npm start"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/ansengarvin/test-frontend:latest
    container_name: frontend
    working_dir: /app
    ports:
      - 5000:3000
    networks:
      - apiserver
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
      - dist:/app/dist
    command: "serve -s dist"
    environment:
      - NODE_ENV="development"
volumes:
  node_modules:
  dist:
