# Dev Docker Compose
# Instantiates the front and back end with environment variables used during development
services:
    frontend:
        environment:
            - NODE_ENV=development
    backend:
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS="./keys/service.json"
            - DB_HOST=mssql
            - DB_PORT=1433
            - DB_USER=sa
            - DB_PASS=YourStrong!Passw0rd
            - NODE_ENV=development
            - FIREBASE_AUTH_EMULATOR_HOST=host.docker.internal:9099
        extra_hosts:
            - host.docker.internal:localhost
