name: cd

on:
    push:
        branches:
            - main

jobs:
    docker:
        name: Build and Push Images
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push docker images
              run: |
                  docker compose -f docker-compose.yaml build
                  docker push ghcr.io/ansengarvin/frontend:${{ github.sha }}
                  docker push ghcr.io/ansengarvin/backend:${{ github.sha }}
