name: cd

on:
    push:
        branches:
            - main

permissions:
    packages: write
    id-token: write
    contents: read

jobs:
    docker:
        name: Update docker images
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Write service.json from secret
              run: echo "${{ secrets.FIREBASE_SERVICE_JSON }}" > backend/etc/keys/service.json

            - name: Build and push docker images
              run: |
                  docker compose -f docker-compose.yaml build
                  docker push ghcr.io/ansengarvin/backend:latest
    frontend:
        name: Deploy frontend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build front end
              run: |
                  npm install
                  npm run build
              working-directory: frontend

            - name: Deploy front end
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_FRONTEND_DEPLOYMENT_TOKEN }}
                  action: upload
                  app_location: "./frontend/dist"
                  skip_app_build: true
