name: cd

on:
    push:
        branches:
            - main

jobs:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker Registry
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${{ github.actor }}
              token: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push backend image
          uses: docker/build-push-action@v4
          with:
              context: ./backend
              file: Dockerfile
              push: true
              tags: ghcr.io/ansengarvin/backend:${{ github.sha }}

        - name: Build and push frontend image
          uses: docker/build-push-action@v4
          with:
              context: ./frontend
              file: Dockerfile
              push: true
              tags: ghcr.io/ansengarvin/frontend:${{github.sha}}
