name: cd

on:
    push:
        branches:
            - main

permissions:
    packages: write

jobs:
    docker:
        name: Update docker images
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Write service.json from secret
              run: echo "${{ secrets.FIREBASE_SERVICE_JSON }}" > backend/etc/keys/service.json

            - name: Build and push docker images
              run: |
                  docker compose -f docker-compose.yaml build
                  docker push ghcr.io/ansengarvin/backend:latest
    frontend:
        name: Deploy frontend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build front end
              run: |
                  npm install
                  npm run build
              working-directory: frontend

            - name: Azure CLI Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Delete old front end files
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                      az storage blob delete-batch \
                      --account-name agkcal \
                      --source '$web' \

            - name: Deploy front end
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                      az storage blob upload-batch \
                      --account-name agkcal \
                      --destination '$web' \
                      --source ./frontend/dist
                      --auth-mode login
