name: cd_back

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"
            - "docker-compose.yaml"
            - ".github/workflows/cd_back.yaml"
            - ".github/workflows/cd_front.yaml"

permissions:
    packages: write

jobs:
    backend:
        name: Update backend docker images
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Write service.json from secret
              run: echo "${{ secrets.FIREBASE_SERVICE_JSON }}" > backend/etc/keys/service.json

            - name: Build and push docker images
              run: |
                  docker compose -f docker-compose.yaml build
                  docker push ghcr.io/ansengarvin/backend:latest
