name: ci

on:
    pull_request:

jobs:
    format:
        name: format (prettier)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  key: ci-format-node-modules-${{ hashFiles('**/package-lock.json') }}
                  path: node_modules

            - name: Install dependencies
              run: npm install

            - name: Check code formatting with prettier
              run: npx prettier . --check

    lint_frontend:
        name: lint frontend (eslint)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  key: ci-lint-frontend-node-modules-${{ hashFiles('**/package-lock.json') }}
                  path: frontend/node_modules

            - name: Install dependencies
              run: npm install
              working-directory: frontend

            - name: Run ESLint
              run: npx eslint .
              working-directory: frontend

    lint_backend:
        name: lint backend (eslint)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  key: ci-lint-backend-node-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install dependencies
              run: npm install
              working-directory: backend

            - name: Run ESLint
              run: npx eslint .
              working-directory: backend

    build_frontend:
        name: validate frontend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  key: ci-build-frontend-node-modules-${{ hashFiles('**/package-lock.json') }}
                  path: frontend/node_modules

            - name: Install dependencies
              run: npm install
              working-directory: frontend

            - name: Run Build
              run: npm run build
              working-directory: frontend
    # TODO: Add a step that speficially verifies the backend.
    # To do so, we'd need to have a local instance of the database.

    docker_compose:
        name: validate docker build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build docker image
              run: docker compose -f docker-compose.yaml build

    api_test:
        name: run api tests (playwright)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  key: ci-test-node-modules-${{ hashFiles('**/package-lock.json') }}
                  path: node_modules

            - name: Install test prerequisites
              run: npm install

            - name: Print docker version
              run: docker --version

            - name: Build dev docker image
              run: docker compose -f docker-compose.yaml -f docker-compose.dev.yaml -f docker-compose.db.yaml up --build -d

            - name: Wait for database setup
              run: sleep 8

            - name: Check docker processes
              run: docker ps -a

            - name: Backend docker logs
              run: docker logs backend

            - name: Initialize database
              run: docker exec -i mssql /opt/mssql-tools18/bin/sqlcmd -S "tcp:mssql,1433" -U sa -P 'YourStrong!Passw0rd' -d master -i /docker-entrypoint-initdb.d/dev.sql -C

            - name: Run playwright tests
              run: npx firebase emulators:exec --project ag-kilocal "npx playwright test"
